export const GET_GRILL_ITEMS_LOADING = "GET_GRILL_ITEMS_LOADING";
export const GET_GRILL_ITEMS_SUCCESS = "GET_GRILL_ITEMS_SUCCESS";
export const GET_GRILL_ITEMS_FAILURE = "GET_GRILL_ITEMS_FAILURE";
export const UPDATE_GRILL_ITEMS_SUCCESS = "UPDATE_GRILL_ITEMS_SUCCESS";
export const UPDATE_GRILL_ITEMS_FAILURE = "UPDATE_GRILL_ITEMS_FAILURE";
export const UPDATE_REMAINING_GRILL_ITEMS = "UPDATE_REMAINING_GRILL_ITEMS";